{% set name = "superset" %}
{% set version = "0.34.0rc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/apache/incubator-{{ name }}/archive/{{ version }}.tar.gz
    sha256: 383979947527aeeaf46b6fa6af61875a90feadb69bafc3bf6928300f2cd2c18a
  - url: https://raw.githubusercontent.com/apache/incubator-{{ name }}/master/LICENSE.txt
    sha256: 600710369a31face16d98c10682bda5d513fe1136f39f0c12f6f6cd9e2ccfe98
  - patches:
      - replace-scripts-with-console.patch

build:
  #noarch: python
  number: 0
  script:
    {% set console_script=os.sep.join(['superset', 'bin', 'superset']) %}
    - pushd {{ name }}{{os.sep}}assets
    - npm ci
    - npm run build
    - popd
    - mv {{ console_script }} {{ console_script}}.py
    - "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [win or py2k]
  entry_points:
    - superset = superset.bin.superset:cli

requirements:
  build:
    - nodejs
  host:
    - python
    - pip
  run:
    - python >=3.6
    # All dependency comments come from github
    # https://raw.githubusercontent.com/apache/incubator-superset/{{version}}/requirements.txt
    - bleach >=3.0.2,<4.0.0
    - celery >=4.3.0,<5.0.0
    - click >=6.0,<7.0.0
    - colorama  #==0.3.9
    - contextlib2 #==0.5.5
    - croniter >=0.3.28
    - cryptography >=2.4.2
    - flask >=1.0.0,<2.0.0
    - flask-appbuilder >=2.1.9,<2.3.0
    - flask-caching #==1.4.0
    - flask-compress #==1.4.0
    - flask-migrate #==2.1.1
    - flask-talisman
    - flask-wtf #==0.14.2
    - geopy #==1.11.0
    - gunicorn <19.9.0 #==19.8.0  # deprecated  # [unix]
    - humanize #==0.5.1
    - isodate #==0.6.0
    - markdown >=3.0
    - pandas >=0.24.2,<0.25.0
    - parsedatetime #==2.0.0
    - pathlib2 #==2.3.0
    - polyline #==1.3.2
    - python-dateutil #==2.6.1
    - python-dotenv
    - python-geohash #==0.8.5
    - pyyaml >=5.1
    - retry >=0.9.2
    - selenium >=3.141.0
    - simplejson >=3.15.0
    - sqlalchemy >=1.3.5,<2.0
    - sqlalchemy-utils >=0.33.2
    - sqlparse >=0.3.0,<0.4
    - wtforms-json #2.2.1
  run_constrained:
    # BigQuery
    #- pybigquery >=0.4.10
    #- pandas_gbq >=0.10.0

    # CORS
    - flask-cors >=2.0.0

    # Gsheets
    # - gsheetsdb >=0.1.9

    # Hive
    - pyhive >=0.6.1
    - tableschema
    - thrift >=0.11.1,<1.0.0

    # MySQL
    - mysqlclient ==1.4.2.post1

    # PostgreSQL
    # DIVERGENCE with setup.py
    # - psycopg2-binary ==2.7.5
    - psycopg2 ==2.7.5

    # Druid
    - pydruid ==0.5.2
    - requests ==2.22.0

    # Presto
    #- pyhive[presto] >=0.4.0

test:
  commands:
    - export SUPERSET_HOME={{PREFIX}}  # [unix]
    - export FLASK_APP='superset'  # [unix]
    - set SUPERSET_HOME={{PREFIX}}  # [win]
    - set FLASK_APP='superset'  # [win]
    - superset --help
    - superset db upgrade
    - superset fab create-admin
        --username admin
        --firstname admin
        --lastname admin
        --email admin@fab.org
        --password admin
    - superset load_examples
    - superset init
  imports:
    - superset

about:
  home: https://superset.incubator.apache.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Apache Superset (incubating) is a modern, enterprise-ready business intelligence web application'

  doc_url: https://superset.incubator.apache.org
  dev_url: https://github.com/apache/incubating-superset

extra:
  recipe-maintainers:
    - sodre
    - CurtLH
