{% set name = "superset" %}
{% set version = "0.33.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/apache/incubator-{{ name }}/archive/{{ version }}.tar.gz
    sha256: cef0c1ff48bf099aca4ed4f2f18ca0eae87f29715b3c314eb07671c30283d7ce
  - url: https://raw.githubusercontent.com/apache/incubator-{{ name }}/master/LICENSE.txt
    sha256: 600710369a31face16d98c10682bda5d513fe1136f39f0c12f6f6cd9e2ccfe98
  - patches:
      - replace-scripts-with-console.patch

build:
  number: 0
  script:
    {% set console_script=os.sep.join(['superset', 'bin', 'superset']) %}
    - mv {{ console_script }} {{ console_script}}.py  # [unix]
    - "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [win or not py36]
  entry_points:
    - superset = superset.bin.superset:cli

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    # All dependency comments come from github
    # https://raw.githubusercontent.com/apache/incubator-superset/{{version}}/requirements.txt
    - bleach >=3.0.2,<4.0.0
    - celery >=4.2.0,<5.0.0
    - click >=6.0,<7.0.0
    - colorama  #==0.3.9
    - contextlib2 #==0.5.5
    - croniter >=0.3.28
    - cryptography >=2.4.2
    - flask >=1.0.0,<2.0.0
    # DIVERGENCE: with setup.py
    - flask-appbuilder >=2,<3
    - flask-caching #==1.4.0
    - flask-compress #==1.4.0
    - flask-migrate #==2.1.1
    - flask-wtf #==0.14.2
    - geopy #==1.11.0
    - gunicorn #==19.8.0  # deprecated
    - humanize #==0.5.1
    - idna #==2.6
    - isodate #==0.6.0
    - markdown >=3.0
    - pandas >=0.18.0,<0.24.0
    - parsedatetime #==2.0.0
    - pathlib2 #==2.3.0
    - polyline #==1.3.2
    - pydruid >=0.4.3
    - python-dateutil #==2.6.1
    - python-geohash #==0.8.5
    - pyyaml >=3.13
    - requests >=2.20.0
    - retry >=0.9.2
    - selenium >=3.141.0
    - simplejson >=3.15.0
    - sqlalchemy >=1.3.1,<2.0
    - sqlalchemy-utils #==0.32.21
    - sqlparse #==0.2.4
    - unicodecsv #==0.14.1
    - wtforms-json #2.2.1

# Add outputs or 
# runtime constraints for superset-with-cors, -with-console-log, -with-hive, -with-presto, -with gsheets

test:
  commands:
    - export SUPERSET_HOME={{PREFIX}}  # [unix]
    - set SUPERSET_HOME={{PREFIX}}  # [win]
    - superset --help
    - superset db upgrade
    - export FLASK_APP='superset'
    - flask fab create-admin
        --username admin
        --firstname admin
        --lastname admin
        --email admin@fab.org
        --password admin
    - superset load_examples
    - superset init
  imports:
    - superset

about:
  home: https://superset.incubator.apache.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Apache Superset (incubating) is a modern, enterprise-ready business intelligence web application'

  doc_url: https://superset.incubator.apache.org
  dev_url: https://github.com/apache/incubating-superset

extra:
  recipe-maintainers:
    - sodre
    - CurtLH
