travis:
  secure:
    BINSTAR_TOKEN: 02moulAhObi/oBzOf/yY5WIgf51VdDMdlUUd6RVX58UBbe6rN4thPoDqKUZrqvrPlET82Nps9J7AOm0db4i/aUmiAciwxwjEoWKFcGDSu4Bn7zHDDEG5kEFBUu0XOIP6E/yyAQW0Iv8sRkQLUZXqWXABSgy3BwukeGcHAoMneaH8YQZwHA/+aIJxt6zN6lVFEtEp1S3OIfygFWWBIVah/YzQDRdOMyk6vHtDgTWNw2Vr9dbFKLUtbz4rT4W51rPidHq0m/lyB0ExUNsxAnyU51t7gxKTkMPZcqGRVBKDH0rNQawkdP16zVKlBeS2GeZQc+2tZ0C+g9+nQhipdKCJHy8yywzyklJA0C8CLNnG0YWHsmh7EgozP/mGR17oWeMJxqCYuLtA5whUjIPb1ASfIrYrYFzM1nq9ae4p4FWIe7Py4GjfcJdeaonaU5l5oTxRxciA6Zcu1aoczBE18q1M/NKqFZxLOOHk54HWvWIYMbojKusGGKfTV2fxCaHk8wYX8oy7kD3NEQvWC5xPy7OUD98qy1UrhA4RhUTjI6E7ZM0oifRD5NB0NWMXdJ3INkFCszVgLvOBdt3l9SOXVpYfGE1yE7maD3pqneMQW9SyGdFuTG+fShFIrcpCWhFBOowaq9j+SawM+y8qN09ipQJsvCf43inOUMAgmnIjH6snSBA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
